
template: Hello, %s!

defaultName: ${DW_DEFAULT_NAME:-olap}

server:
  applicationConnectors:
    - type: http
      port: 6080
  adminConnectors:
    - type: http
      port: 6081
   
httpClient:
  timeout: 5000ms
  connectionTimeout: 5000ms
  timeToLive: 1h
  cookiesEnabled: false
  maxConnections: 1024
  maxConnectionsPerRoute: 1024
  keepAlive: 0ms
  retries: 0
  userAgent: <application name> (<client name>)

database1:
   driverClass: com.mysql.cj.jdbc.Driver
   user: root
   password: 123456
   url: jdbc:mysql://localhost:3309/spider?autoReconnect=true&characterEncoding=utf-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
   maxWaitForConnection: 60s
   validationQuery: " SELECT 1"
   validationQueryTimeout: 60s
   minSize: 4
   maxSize: 32
   checkConnectionWhileIdle: false
   evictionInterval: 30s
   minIdleTime: 1 minute
     
logging:
  level: DEBUG
  loggers:
    com.zheng.spider: DEBUG
    org.jdbi.v3:
      level: DEBUG
    org.htmlunit:
      level: warn  
  appenders:
    - type: console
    - type: file
      threshold: INFOls
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /tmp/spider.log
      archivedLogFilenamePattern: /tmp/spider-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: GMT+8
      maxFileSize: 10MiB   

application:
  isOutSide: 0
  #spider:
  #  - bussType: okcis
  #    firstPage:
  #      url: https://www.okcis.cn/searched/
        
       
            
        
       
      
 